### ISSUE TITLE
Keys Changing via hover and scroll

### ISSUE THREAD

**Issue by ThisUsedToBeAnEmail** [Mottie/Keyboard#665]
Hello, So during some testing of your plugin I have encountered the following. I'm wondering whether you are aware and if there is some work around I can implement locally to prevent.

https://vimeo.com/265301679

To reproduce you just need to hover over a key and then scroll up and down and some keys will duplicate and jump position.

**Comment by ThisUsedToBeAnEmail** [comment]
It occurs on my mac in all browsers and it was originally picked up in windows by one of my tester.

I can also replicate this here https://mottie.github.io/Keyboard/index.html.
<img width="994" alt="screen shot 2018-04-18 at 23 37 11" src="https://user-images.githubusercontent.com/16151791/38945717-815761e6-4361-11e8-9e58-27d477f77f04.png">

I am scrolling on my mac touch pad I believe in windows they were using a mouse. I will try your fix and see if that resolves it.

Regards

**Comment by ThisUsedToBeAnEmail** [comment]
Apologies for the delay but turning off useWheel seems to have resolved the problem. Thanks!

**Comment by Mottie** [comment]
It sounds like this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by ThisUsedToBeAnEmail** [comment]
Well it's closed in the sense we have found a work around I think initial bug still exists though.

**Comment by Mottie** [comment]
Odd that I still can't duplicate it.

**Comment by ThisUsedToBeAnEmail** [comment]
Can confirm as just replicated - 

<img width="192" alt="screen shot 2018-07-06 at 01 58 14" src="https://user-images.githubusercontent.com/16151791/42342422-3855093e-80c0-11e8-9056-4c7a011e51e0.png">

**Comment by Mottie** [comment]
My mousewheel scroll was set to only scroll a few lines at a time, so once I switched to a mouse with hyper-scrolling, I started seeing this problem.

I've only updated the main `jquery.keyboard.js` file. Please test it and let me know

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
